{% set name = "sagemaker_containers" %}
{% set version = "2.5.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92b14ce9064c5b19bfbbb015d98dcd42977415fb0eadd90bfc2d7c5063f40a11

build:
  number: 0
  entry_points:
    - serve=sagemaker_containers.cli.serve:main
    - train=sagemaker_containers.cli.train:main
  script: "{{ PYTHON }} -m pip install . -vv "
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - boto3
    - flask
    - gevent
    - gunicorn
    - inotify_simple
    - numpy
    - paramiko
    - pip
    - psutil
    - python
    - retrying
    - six
    - typing
    - werkzeug

test:
  imports:
    - sagemaker_containers
    - sagemaker_containers.beta
    - sagemaker_containers.beta.framework
    - sagemaker_containers.cli
    - sagemaker_containers.etc  # [py>=36]

about:
  home: "https://github.com/aws/sagemaker-containers/"
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "Open source library for creating containers to run on Amazon SageMaker."
  doc_url: "https://pypi.org/project/sagemaker-containers/"
  dev_url: "https://github.com/aws/sagemaker-containers/"

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - rluria14
