{% set name = "sagemaker_containers" %}
{% set version = "2.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version
    }}.tar.gz
  sha256: b8183349420ab5ad478ef19eb91a23360f73ebd2e0d014249f70f5125389bc56

build:
  number: 0
  entry_points:
    - serve=sagemaker_containers.cli.serve:main
    - train=sagemaker_containers.cli.train:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - boto3
    - flask
    - gevent
    - gunicorn
    - inotify_simple
    - numpy
    - paramiko
    - psutil
    - retrying
    - six
    - typing  # [py27]
    - werkzeug

test:
  requires:
    - scipy
    - protobuf3-to-dict
    - pip
  imports:
    - sagemaker_containers
    - sagemaker_containers.beta
    - sagemaker_containers.beta.framework
    - sagemaker_containers.cli
    - sagemaker_containers.etc  # [py>=36]

  commands:
    - python -m pip check
about:
  home: https://github.com/aws/sagemaker-containers/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for creating containers to run on Amazon SageMaker.
  doc_url: https://pypi.org/project/sagemaker-containers/
  dev_url: https://github.com/aws/sagemaker-containers/

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - rluria14
